In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris.data_module

'sklearn.datasets.data'

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target , test_size =0.2)

In [10]:
x_train

array([[6.4, 2.9, 4.3, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.1, 2.8, 4. , 1.3],
       [6.7, 3.1, 5.6, 2.4],
       [5.5, 3.5, 1.3, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [6.3, 2.7, 4.9, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [5.5, 4.2, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [6.5, 2.8, 4.6, 1.5],
       [4.6, 3.6, 1. , 0.2],
       [7.2, 3.2, 6. , 1.8],
       [4.8, 3. , 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.8, 3. , 5.5, 2.1],
       [6.5, 3. , 5.8, 2.2],
       [5. , 3.2, 1.2, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3. , 5.2, 2.3],
       [5.7, 3. , 4.2, 1.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [7.9, 3.8, 6.4, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [7.7, 2.6, 6.9, 2.3],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 3. , 4.6, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [5.4, 3

In [11]:
x_test

array([[5.6, 3. , 4.5, 1.5],
       [5. , 3.5, 1.3, 0.3],
       [5.8, 2.8, 5.1, 2.4],
       [5.1, 3.7, 1.5, 0.4],
       [4.9, 3.1, 1.5, 0.1],
       [6.3, 3.3, 6. , 2.5],
       [6. , 2.2, 5. , 1.5],
       [5.7, 4.4, 1.5, 0.4],
       [5.3, 3.7, 1.5, 0.2],
       [6.4, 2.7, 5.3, 1.9],
       [5.6, 3. , 4.1, 1.3],
       [6.4, 3.2, 5.3, 2.3],
       [5. , 3.3, 1.4, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [5. , 3.6, 1.4, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [6.4, 3.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.8, 2.6, 4. , 1.2],
       [5.1, 3.5, 1.4, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 3.4, 1.4, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [5.4, 3. , 4.5, 1.5],
       [6. , 2.2, 4. , 1. ],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.3, 4.4, 1.3],
       [5.5, 2.4, 3.8, 1.1]])

In [12]:
y_train

array([1, 2, 2, 1, 2, 0, 1, 2, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 1, 2, 2, 0,
       2, 2, 1, 0, 0, 2, 2, 2, 2, 1, 1, 2, 0, 2, 1, 0, 2, 1, 1, 2, 2, 2,
       2, 1, 2, 2, 1, 1, 2, 0, 1, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 1, 2,
       2, 2, 0, 1, 0, 0, 0, 1, 0, 2, 1, 0, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0,
       1, 1, 0, 0, 1, 2, 2, 0, 2, 0, 1, 1, 0, 2, 1, 0, 1, 0, 1, 2, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 2, 2])

In [13]:
y_test

array([1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 1, 2, 0, 0, 2, 2, 0, 2, 1, 2, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1])

In [19]:
from tensorflow.keras.models import Sequential

In [20]:
from tensorflow.keras.layers import Dense

In [21]:
model = Sequential()

In [24]:
input_layer = Dense(4, input_shape=(4,))

C:\Users\kunal  kumar  pandey\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model.add(input_layer)

In [26]:
hidden_layer = Dense(4 , activation = 'relu')

In [27]:
model.add(hidden_layer)

In [28]:
output_layer = Dense(3 , activation='softmax')

In [29]:
model.add(output_layer)

In [31]:
# complie the model means load the model inot memory , model not run byut abilabel in memeory
model.compile(loss = 'sparse_categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])

In [32]:
# train the model
model.fit(x_train, y_train , epochs = 300 , batch_size=4)

Epoch 1/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.3333 - loss: 1.5446
Epoch 2/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3333 - loss: 1.1623
Epoch 3/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4500 - loss: 1.0255
Epoch 4/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5583 - loss: 0.9751
Epoch 5/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5167 - loss: 0.9337
Epoch 6/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5167 - loss: 0.9022
Epoch 7/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4833 - loss: 0.8711
Epoch 8/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5333 - loss: 0.8471
Epoch 9/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3667 - loss: 0.8244
Epoch 10/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4417 - loss: 0.7993
Epoch 11/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4333 - loss: 0.7777
Epoch 12/300
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accurac

In [33]:
# Evaulate the model
val_loss , val_acc = model.evaluate(x_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 424ms/step - accuracy: 1.0000 - loss: 0.0198


In [34]:
val_loss

0.0198495052754879

In [35]:
val_acc

1.0

In [37]:
import numpy as np

In [38]:
arr = np.array([[5.1 , 3.5 , 1.4, 0.2]])

In [39]:
result = model.predict(arr)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step


In [40]:
result

array([[9.9976367e-01, 2.3628490e-04, 1.4295791e-15]], dtype=float32)

In [41]:
print(np.argmax(result))

0


In [42]:
model.save("model.keras")

In [43]:
from tensorflow.keras.models import load_model

load = load_model("model.keras")

In [44]:
load.predict(arr)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step


array([[9.9976367e-01, 2.3628490e-04, 1.4295791e-15]], dtype=float32)

In [45]:
np.argmax(load.predict(arr))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step


0