In [1]:
pip install tensorflow

  Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
   ---------------------------------------- 0.0/331.7 MB ? eta -:--:--
   ---------------------------------------- 1.6/331.7 MB 12.0 MB/s eta 0:00:28
    --------------------------------------- 4.2/331.7 MB 11.4 MB/s eta 0:00:29
    --------------------------------------- 6.8/331.7 MB 11.7 MB/s eta 0:00:28
   - -------------------------------------- 9.4/331.7 MB 11.5 MB/s eta 0:00:28
   - -------------------------------------- 12.1/331.7 MB 11.6 MB/s eta 0:00:28
   - -------------------------------------- 14.4/331.7 MB 11.8 MB/s eta 0:00:27
   -- ------------------------------------- 17.0/331.7 MB 11.7 MB/s eta 0:00:27
   -- ------------------------------------- 19.7/331.7 MB 11.7 MB/s eta 0:00:27
   -- ------------------------------------- 22.0/331.7 MB 11.6 MB/s eta 0:00:

  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2025.7.0 which is incompatible.
datasets 4.0.0 requires huggingface-hub>=0.24.0, but you have huggingface-hub 0.23.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.6 which is incompatible.
gradio 4.26.0 requires markupsafe~=2.0, but you have markupsafe 3.0.2 which is incompatible.
gradio 4.26.0 requires numpy~=1.0, but you have numpy 2.2.6 which is incompatible.
pandas 2.1.3 requires numpy<2,>=1.22.4; python_version < "3.11", but you have numpy 2.2.6 which is incompatible.
peft 0.16.0 requires huggingface_hub>=0.25.0, but you have huggingface-hub 0.23.0 which is incompatible.
scipy 1.11.4 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.2.6 which is incomp

In [1]:
import numpy
import pandas
import tensorflow as tf

print("NumPy:", numpy.__version__)
print("Pandas:", pandas.__version__)
print("TensorFlow:", tf.__version__)

NumPy: 1.26.4
Pandas: 2.1.3
TensorFlow: 2.20.0


# constant tensorflow

In [2]:
c1 = tf.constant(10)

In [3]:
c1

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
c2 = tf.constant(10, tf.int16)

In [5]:
c2

<tf.Tensor: shape=(), dtype=int16, numpy=10>

In [6]:
c3 = tf.constant(10 , tf.float32 , name = 'my constant')

In [7]:
c3

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [9]:
c4 = tf.constant('hello kunal pandey')

In [10]:
c4

<tf.Tensor: shape=(), dtype=string, numpy=b'hello kunal pandey'>

# varibale tensor

In [12]:
v1 = tf.Variable(25)
print(v1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>


In [13]:
v1.assign(45)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=45>

In [14]:
new_var = 100
v1.assign(new_var)
print(v1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>


In [15]:
v2 = tf.Variable("kunal Pandey")
v2

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'kunal Pandey'>

# create tansor with array

In [16]:
arr1 = tf.constant([10, 20, 30, 40])
print(arr1)

tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)


In [17]:
arr2 = tf.constant([[10,12,13,14],[10,13,15,16]])
print(arr2)

tf.Tensor(
[[10 12 13 14]
 [10 13 15 16]], shape=(2, 4), dtype=int32)


In [19]:
# create 2 row and 3 columns
arr3 = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])
print(arr3)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]], shape=(2, 2, 3), dtype=int32)


In [21]:
arr3.shape

TensorShape([2, 2, 3])

In [22]:
arr3.dtype

tf.int32

In [26]:
a = tf.constant(10)
b = tf.constant(20)
c = a + b

print(c)
print(c.numpy())

tf.Tensor(30, shape=(), dtype=int32)
30


In [29]:
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)
power = tf.pow(a, b)
# exp = tf.exp(a)
sqr = tf.sqrt(tf.cast(a, tf.float32))  # sqrt needs float

print("Add:", add.numpy())
print("Subtract:", sub.numpy())
print("Multiply:", mul.numpy())
print("Divide:", div.numpy())
print("Power:", power.numpy())
# print("Exp:", exp.numpy())
print("Sqrt:", sqr.numpy())

Add: 30
Subtract: -10
Multiply: 200
Divide: 0.5
Power: 1661992960
Sqrt: 3.1622777
